
version: '3.4'

services:
  avhmessagebrokerworker:
    image: avhmessagebrokerworker
    build:
      context: .
      dockerfile: AVH.MessageBroker.Worker/Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
